services:
  achlys:
    restart: unless-stopped
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      STEAM_API_KEY: ${STEAM_API_KEY?Missing Steam API key}
      PORT: ${PORT:-3000}
      RUST_LOG: ${RUST_LOG:-info}
    ports:
      - "127.0.0.1:${PORT:-3000}:${PORT:-3000}"
